# vim: filetype=sh

### Shipped as files
#
# Paths are from a podman sweep of debian, ubuntu, fedora, arch, alpine and
# NixOS; XDG_DATA_DIRS was empty on every one. The framework must come first.

# Load-bearing on Debian and Ubuntu, which ship the framework but leave the
# block in /etc/bash.bashrc commented out. VERSINFO is assigned at the top of
# the framework itself; _init_completion is the wrong test, living in a compat
# shim upstream deprecated and a distro need not load.
if [ -z "${BASH_COMPLETION_VERSINFO[*]-}" ]; then
	if [ -f /usr/share/bash-completion/bash_completion ]; then
		source /usr/share/bash-completion/bash_completion
	fi
fi

# Two blocks, not one elif chain: completion and prompt are different files and
# we want both.
if ! declare -F __git_main >/dev/null; then
	if [ -f /usr/share/bash-completion/completions/git ]; then
		source /usr/share/bash-completion/completions/git
	elif [ -f /run/current-system/sw/share/bash-completion/completions/git ]; then
		source /run/current-system/sw/share/bash-completion/completions/git
	fi
fi

# Not a completion, but git ships __git_ps1 alongside them. Alpine packages no
# copy; Debian, Ubuntu and openSUSE keep theirs outside every data root and
# load it from /etc/bash_completion.d, which is what the guard catches.
if ! declare -F __git_ps1 >/dev/null; then
	if [ -f /usr/share/git-core/contrib/completion/git-prompt.sh ]; then
		source /usr/share/git-core/contrib/completion/git-prompt.sh
	elif [ -f /usr/share/git/completion/git-prompt.sh ]; then
		source /usr/share/git/completion/git-prompt.sh
	elif [ -f /run/current-system/sw/share/bash-completion/completions/git-prompt.sh ]; then
		source /run/current-system/sw/share/bash-completion/completions/git-prompt.sh
	fi
fi

### Generated by the tool

if command -v kubectl &>/dev/null; then
	source <(kubectl completion bash)
fi

if command -v devpod &>/dev/null; then
	source <(devpod completion bash)
fi

if command -v minikube &>/dev/null; then
	source <(minikube completion bash)
fi

if command -v rustup &>/dev/null; then
	source <(rustup completions bash)
	source <(rustup completions bash cargo)
fi

if command -v goldwarden &>/dev/null; then
	source <(goldwarden completion bash)
fi

if command -v deno &>/dev/null; then
	source <(deno completions bash)
fi

if command -v helm &>/dev/null; then
	source <(helm completion bash)
fi

if command -v mongocli &>/dev/null; then
	source <(mongocli completion bash)
fi

if command -v fnm &>/dev/null; then
	source <(fnm completions --shell bash)
fi

if command -v nono &>/dev/null; then
	source <(nono completion bash)
fi

if command -v matchlock &>/dev/null; then
	source <(matchlock completion bash)
fi

### Delegated to the tool

if command -v terraform &>/dev/null; then
	complete -C "$(command -v terraform)" terraform
fi

if command -v register-python-argcomplete &>/dev/null && command -v pipx &>/dev/null; then
	eval "$(register-python-argcomplete pipx)"
fi

### Wrappers

# git shells out to the subcommand to enumerate its flags, and $HOME is not a
# repository -- the dotfiles repo is bare at ~/.dotfiles. Without this,
# `dot commit --a<TAB>` completes only subcommand names.
if declare -F __git_complete >/dev/null; then
	_dot_main() {
		GIT_DIR=$HOME/.dotfiles GIT_WORK_TREE=$HOME __git_main "$@"
	}
	__git_complete dot _dot_main
fi

# The agent entrypoints take `nono run` arguments up to `--`, so rewrite the
# line and hand it to nono's own completion.
if declare -F _nono >/dev/null; then
	_agent_complete() {
		if [[ " ${COMP_WORDS[*]:1:COMP_CWORD-1} " == *" -- "* ]]; then
			return
		fi
		COMP_WORDS=(nono run "${COMP_WORDS[@]:1}")
		((COMP_CWORD += 1))
		_nono nono "$2" "$3"
	}

	# Same options nono registers itself with: `_nono` emits no COMPREPLY for
	# path-valued flags and leans on `-o default` for the filename fallback.
	for _c in ncl npi nop; do
		if declare -F "$_c" >/dev/null; then
			complete -o bashdefault -o default -o nosort -F _agent_complete "$_c"
		fi
	done
	unset _c
elif command -v nono &>/dev/null; then
	echo ".completions.bash: nono completion no longer defines _nono" >&2
fi
