#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if command -v dconf >/dev/null; then
	echo "Dumping extension settings"
	dconf dump /org/gnome/shell/extensions/ >~/.local/share/gnome-shell/extension-settings.dconf
	git add ~/.local/share/gnome-shell/extension-settings.dconf
fi
