vim.pack.add({
    { src = "https://github.com/folke/snacks.nvim" },
})

-- bare dotfiles repo has no $HOME/.git, snacks' watcher logs ENOENT
local ok, baredot = pcall(require, "baredot")
local explorer_watch = not (ok and baredot.is_enabled())

require("snacks").setup({
    explorer = { enabled = true },
    terminal = {
        win = {
            position = "float",
        },
    },
    picker = {
        ui_select = true, -- route vim.ui.select through the picker
        sources = {
            files = { hidden = true },
            grep = { hidden = true },
            explorer = {
                layout = { preview = "main" },
                jump = { close = true },
                hidden = true,
                ignored = true,
                watch = explorer_watch,
            },
        },
    },
})

-- Explorer
vim.keymap.set("n", "<leader>e", function()
    Snacks.explorer()
end, { desc = "Explorer" })

-- Terminal
vim.keymap.set({ "n", "t" }, "<c-/>", function()
    Snacks.terminal()
end, { desc = "Terminal" })

-- Buffer deletion (preserves window layout, only listed buffers)
vim.keymap.set("n", "<leader><BS>", function()
    Snacks.bufdelete()
end, { desc = "Delete buffer" })
vim.keymap.set("n", "<leader>bo", function()
    Snacks.bufdelete.other()
end, { desc = "Delete other buffers" })
vim.keymap.set("n", "<leader>bi", function()
    Snacks.bufdelete.invisible()
end, { desc = "Delete invisible buffers" })
vim.keymap.set("n", "<leader>ba", function()
    Snacks.bufdelete.all()
end, { desc = "Delete all buffers" })

-- Git
require("which-key").add({ "<leader>g", group = "git" })
vim.keymap.set("n", "<leader>gg", function()
    Snacks.lazygit()
end, { desc = "Lazygit" })

vim.keymap.set({ "n", "x" }, "<leader>gh", function()
    Snacks.gitbrowse()
end, { desc = "Git Browse (open)" })
vim.keymap.set({ "n", "x" }, "<leader>gH", function()
    local function open(url)
        vim.fn.setreg("+", url)
    end
    Snacks.gitbrowse({ notify = false, open = open })
end, { desc = "Git Browse (copy)" })

vim.keymap.set("n", "<leader>gb", function()
    Snacks.picker.git_log_line()
end, { desc = "Git Blame Line" })
vim.keymap.set("n", "<leader>gf", function()
    Snacks.picker.git_log_file()
end, { desc = "Git Current File History" })
vim.keymap.set("n", "<leader>gl", function()
    Snacks.picker.git_log()
end, { desc = "Git Log" })

-- git pickers
vim.keymap.set("n", "<leader>gd", function()
    Snacks.picker.git_diff()
end, { desc = "Git Diff (hunks)" })
vim.keymap.set("n", "<leader>gD", function()
    Snacks.picker.git_diff({ base = "origin", group = true })
end, { desc = "Git Diff (origin)" })
vim.keymap.set("n", "<leader>gs", function()
    Snacks.picker.git_status()
end, { desc = "Git Status" })
vim.keymap.set("n", "<leader>gS", function()
    Snacks.picker.git_stash()
end, { desc = "Git Stash" })
vim.keymap.set("n", "<leader>gi", function()
    Snacks.picker.gh_issue()
end, { desc = "GitHub Issues (open)" })
vim.keymap.set("n", "<leader>gI", function()
    Snacks.picker.gh_issue({ state = "all" })
end, { desc = "GitHub Issues (all)" })
vim.keymap.set("n", "<leader>gp", function()
    Snacks.picker.gh_pr()
end, { desc = "GitHub Pull Requests (open)" })
vim.keymap.set("n", "<leader>gP", function()
    Snacks.picker.gh_pr({ state = "all" })
end, { desc = "GitHub Pull Requests (all)" })

-- Picker (top-level)
vim.keymap.set("n", "<leader>,", function()
    Snacks.picker.buffers()
end, { desc = "Buffers" })
vim.keymap.set("n", "<leader>/", function()
    Snacks.picker.grep()
end, { desc = "Grep" })
vim.keymap.set("n", "<leader>:", function()
    Snacks.picker.command_history()
end, { desc = "Command History" })
vim.keymap.set("n", "<leader><space>", function()
    Snacks.picker.files()
end, { desc = "Find Files" })
vim.keymap.set("n", "<leader>n", function()
    Snacks.picker.notifications()
end, { desc = "Notification History" })

-- Find
require("which-key").add({ "<leader>f", group = "find" })
vim.keymap.set("n", "<leader>fb", function()
    Snacks.picker.buffers()
end, { desc = "Buffers" })
vim.keymap.set("n", "<leader>fB", function()
    Snacks.picker.buffers({ hidden = true, nofile = true })
end, { desc = "Buffers (all)" })
vim.keymap.set("n", "<leader>fc", function()
    Snacks.picker.files({ cwd = vim.fn.stdpath("config") })
end, { desc = "Find Config File" })
vim.keymap.set("n", "<leader>ff", function()
    Snacks.picker.files()
end, { desc = "Find Files" })
vim.keymap.set("n", "<leader>fg", function()
    Snacks.picker.git_files()
end, { desc = "Find Files (git-files)" })
vim.keymap.set("n", "<leader>fr", function()
    Snacks.picker.recent()
end, { desc = "Recent" })
vim.keymap.set("n", "<leader>fR", function()
    Snacks.picker.recent({ filter = { cwd = true } })
end, { desc = "Recent (cwd)" })
vim.keymap.set("n", "<leader>fp", function()
    Snacks.picker.projects()
end, { desc = "Projects" })

-- Grep
vim.keymap.set("n", "<leader>sb", function()
    Snacks.picker.lines()
end, { desc = "Buffer Lines" })
vim.keymap.set("n", "<leader>sB", function()
    Snacks.picker.grep_buffers()
end, { desc = "Grep Open Buffers" })
vim.keymap.set("n", "<leader>sg", function()
    Snacks.picker.grep()
end, { desc = "Grep" })
vim.keymap.set("n", "<leader>sp", function()
    Snacks.picker.lazy()
end, { desc = "Search for Plugin Spec" })
vim.keymap.set({ "n", "x" }, "<leader>sw", function()
    Snacks.picker.grep_word()
end, { desc = "Visual selection or word" })

-- Search
require("which-key").add({ "<leader>s", group = "search" })
vim.keymap.set("n", '<leader>s"', function()
    Snacks.picker.registers()
end, { desc = "Registers" })
vim.keymap.set("n", "<leader>s/", function()
    Snacks.picker.search_history()
end, { desc = "Search History" })
vim.keymap.set("n", "<leader>sa", function()
    Snacks.picker.autocmds()
end, { desc = "Autocmds" })
vim.keymap.set("n", "<leader>sc", function()
    Snacks.picker.command_history()
end, { desc = "Command History" })
vim.keymap.set("n", "<leader>sC", function()
    Snacks.picker.commands()
end, { desc = "Commands" })
vim.keymap.set("n", "<leader>sd", function()
    Snacks.picker.diagnostics()
end, { desc = "Diagnostics" })
vim.keymap.set("n", "<leader>sD", function()
    Snacks.picker.diagnostics_buffer()
end, { desc = "Buffer Diagnostics" })
vim.keymap.set("n", "<leader>sh", function()
    Snacks.picker.help()
end, { desc = "Help Pages" })
vim.keymap.set("n", "<leader>sH", function()
    Snacks.picker.highlights()
end, { desc = "Highlights" })
vim.keymap.set("n", "<leader>si", function()
    Snacks.picker.icons()
end, { desc = "Icons" })
vim.keymap.set("n", "<leader>sj", function()
    Snacks.picker.jumps()
end, { desc = "Jumps" })
vim.keymap.set("n", "<leader>sk", function()
    Snacks.picker.keymaps()
end, { desc = "Keymaps" })
vim.keymap.set("n", "<leader>sl", function()
    Snacks.picker.loclist()
end, { desc = "Location List" })
vim.keymap.set("n", "<leader>sM", function()
    Snacks.picker.man()
end, { desc = "Man Pages" })
vim.keymap.set("n", "<leader>sm", function()
    Snacks.picker.marks()
end, { desc = "Marks" })
vim.keymap.set("n", "<leader>sR", function()
    Snacks.picker.resume()
end, { desc = "Resume" })
vim.keymap.set("n", "<leader>sq", function()
    Snacks.picker.qflist()
end, { desc = "Quickfix List" })
vim.keymap.set("n", "<leader>su", function()
    Snacks.picker.undo()
end, { desc = "Undotree" })

-- ui
vim.keymap.set("n", "<leader>uC", function()
    Snacks.picker.colorschemes()
end, { desc = "Colorschemes" })

-- LSP (LazyVim binds these per-server; mirror exactly on attach)
vim.api.nvim_create_autocmd("LspAttach", {
    group = vim.api.nvim_create_augroup("config_snacks_lsp_keymaps", { clear = true }),
    callback = function(ev)
        vim.keymap.set("n", "gd", function()
            Snacks.picker.lsp_definitions()
        end, { buffer = ev.buf, desc = "Goto Definition" })
        vim.keymap.set("n", "grr", function()
            Snacks.picker.lsp_references()
        end, { buffer = ev.buf, nowait = true, desc = "References" })
        vim.keymap.set("n", "gI", function()
            Snacks.picker.lsp_implementations()
        end, { buffer = ev.buf, desc = "Goto Implementation" })
        vim.keymap.set("n", "gri", function()
            Snacks.picker.lsp_implementations()
        end, { buffer = ev.buf, desc = "Goto Implementation" })
        vim.keymap.set("n", "gy", function()
            Snacks.picker.lsp_type_definitions()
        end, { buffer = ev.buf, desc = "Goto T[y]pe Definition" })
        vim.keymap.set("n", "grt", function()
            Snacks.picker.lsp_type_definitions()
        end, { buffer = ev.buf, desc = "Goto Type Definition" })
        vim.keymap.set("n", "<leader>ss", function()
            Snacks.picker.lsp_symbols()
        end, { buffer = ev.buf, desc = "LSP Symbols" })
        vim.keymap.set("n", "<leader>sS", function()
            Snacks.picker.lsp_workspace_symbols()
        end, { buffer = ev.buf, desc = "LSP Workspace Symbols" })
        vim.keymap.set("n", "gai", function()
            Snacks.picker.lsp_incoming_calls()
        end, { buffer = ev.buf, desc = "C[a]lls Incoming" })
        vim.keymap.set("n", "gao", function()
            Snacks.picker.lsp_outgoing_calls()
        end, { buffer = ev.buf, desc = "C[a]lls Outgoing" })
    end,
})
