# https://github.com/alacritty/alacritty-theme/blob/master/themes/gruvbox_dark.toml
# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black = '#282828'
red = '#cc241d'
green = '#98971a'
yellow = '#d79921'
blue = '#458588'
magenta = '#b16286'
cyan = '#689d6a'
white = '#a89984'

# Bright colors
[colors.bright]
black = '#928374'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white = '#ebdbb2'

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 12.0

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true
decorations = "none"

[window.padding]
x = 4
y = 4

[scrolling]
history = 100000

# See https://wiki.archlinux.org/title/Alacritty#Spawn_new_instance_in_same_directory
[keyboard]
bindings = [
    { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]

[env]
BAT_THEME = "TwoDark"
